myrating_url.settings:
  type: config_object
  label: 'Рейтинг страниц'
  mapping:
    count_stars:
      type: integer
      label: 'Количество звезд'
    text_chema_org:
      type: text
      label: 'Text chema org'
    text_submit:
      type: label
      label: 'Text submit'

block.settings.myrating_url:
  type: block_settings
  label: 'Rating for url'
  mapping:
    text_chema_org:
      type: text
      label: 'Text chema org'
    text_submit:
      type: label
      label: 'Text submit'


